package com.abrahms.ShoppingListApp.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;

import java.util.Date;
import java.util.UUID;

@Entity
public class ShoppingList {

    @Id
    @GeneratedValue // If you want the ID to be generated by the application
    @Column(columnDefinition = "uniqueidentifier")
    private UUID id;

    @Column(length = 32, nullable = false)
    private String name;

    public UUID getId() {
        return id;
    }

    @Column
    private Date date;

    public void setId(UUID id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public ShoppingList(UUID id, String name, Date date) {
        this.id = id;
        this.name = name;
        this.date = date;
    }

    public ShoppingList() {
    }
}