package com.abrahms.ShoppingListApp.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;

import java.util.UUID;

@Entity
public class ShoppingListItem {
    @Id
    @GeneratedValue // If you want the ID to be generated by the application
    @Column(columnDefinition = "uniqueidentifier")
    private UUID id;

    @GeneratedValue // If you want the ID to be generated by the application
    @Column(columnDefinition = "uniqueidentifier", nullable = false)
    private UUID shoppingListID;

    @GeneratedValue // If you want the ID to be generated by the application
    @Column(columnDefinition = "uniqueidentifier", nullable = false)
    private UUID storeProductID;

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getShoppingListID() {
        return shoppingListID;
    }

    public void setShoppingListID(UUID shoppingListID) {
        this.shoppingListID = shoppingListID;
    }

    public UUID getStoreProductID() {
        return storeProductID;
    }

    public void setStoreProductID(UUID storeProductID) {
        this.storeProductID = storeProductID;
    }

    public ShoppingListItem(UUID shoppingListID, UUID storeProductID) {
        this.shoppingListID = shoppingListID;
        this.storeProductID = storeProductID;
    }

    public ShoppingListItem() {
    }
}
