package com.abrahms.ShoppingListApp.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;

import java.util.UUID;

@Entity
public class StoreProduct {

    @Id
    @GeneratedValue
    @Column(columnDefinition = "uniqueidentifier")
    private UUID id;

    @Column(length = 32, nullable = false)
    private String productName;

    @Column(length = 32, nullable = false)
    private String brandName;

    private Double price;

    @GeneratedValue // If you want the ID to be generated by the application
    @Column(columnDefinition = "uniqueidentifier", nullable = false)
    private UUID storeId;

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public String getBrandName() {
        return brandName;
    }

    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public UUID getStoreId() {
        return storeId;
    }

    public void setStoreId(UUID storeId) {
        this.storeId = storeId;
    }

    public StoreProduct(UUID id, String productName, String brandName, Double price, UUID storeId) {
        this.id = id;
        this.productName = productName;
        this.brandName = brandName;
        this.price = price;
        this.storeId = storeId;
    }

    public StoreProduct() {
    }
}
