DROP TABLE ShoppingListItem;
DROP TABLE ShoppingList;
DROP TABLE StoreProduct;
DROP TABLE Store;


CREATE TABLE Store (
	ID UNIQUEIDENTIFIER PRIMARY KEY default NEWID(),
	Name VARCHAR(32) NOT NULL
)

CREATE TABLE ShoppingList (
	ID UNIQUEIDENTIFIER PRIMARY KEY default NEWID(),
    Name VARCHAR(32) NOT NULL,
	Date DATE
)

CREATE TABLE StoreProduct (
	ID UNIQUEIDENTIFIER PRIMARY KEY default NEWID(),
    ProductName VARCHAR(32) NOT NULL,
	BrandName VARCHAR(32) NOT NULL,
    Price DECIMAL(20,2)
)

CREATE TABLE ShoppingListItem (
    ID UNIQUEIDENTIFIER PRIMARY KEY default NEWID(),
    ShoppingListID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES ShoppingList(ID),
    StoreProductID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES StoreProduct(ID),
)